[package]
name = "sipx-v1-endpoint-consumer"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sipx-call = { version = "=1.0.0", features = ["dtls"] }
sipx-sip = "=1.0.0"
sipx-transport = "=1.0.0"
sipx-ua = "=1.0.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
