//! Application-owned requests inside an established dialog.
//!
//! The state-machine-owned methods stay in [`Call::handle`](crate::Call::handle). This module
//! owns only the bounded request snapshot and the exactly-once response capability described by
//! `docs/specs/dialog-extensions.md`.

use std::future::Future;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::time::Duration;

use bytes::Bytes;
use sipx_sip::build::ResponseBuilder;
use sipx_sip::transaction::TransactionKey;
use sipx_sip::{Header, HeaderName, Headers, Method, Request, StatusCode};
use sipx_transport::Handle;
use tokio::sync::Notify;

use crate::error::{Error, Result};

/// Largest body the application-owned dialog path will retain.
pub const MAX_APPLICATION_BODY: usize = 64 * 1024;

/// How long an application may retain an unanswered server transaction.
const RESPONSE_DEADLINE: Duration = Duration::from_secs(32);

/// One application-owned request received inside a live dialog.
///
/// Clones share one exactly-once response capability. Dropping the final unanswered clone produces
/// a bounded `500` refusal.
#[derive(Debug, Clone)]
pub struct ApplicationRequest {
    method: Method,
    headers: Headers,
    body: Bytes,
    response: ResponseCapability,
}

impl ApplicationRequest {
    pub(crate) fn new(endpoint: Handle, key: TransactionKey, request: &Request) -> Self {
        let response = ResponseCapability::new(endpoint, key, request.clone());
        Self {
            method: request.method.clone(),
            headers: request.headers.clone(),
            body: Bytes::copy_from_slice(request.body()),
            response,
        }
    }

    /// The admitted request method.
    #[must_use]
    pub fn method(&self) -> &Method {
        &self.method
    }

    /// The complete parser-validated header collection, in wire order.
    #[must_use]
    pub fn headers(&self) -> &Headers {
        &self.headers
    }

    /// The bounded request body.
    #[must_use]
    pub fn body(&self) -> &[u8] {
        &self.body
    }

    /// Send the one final response owned by this request.
    ///
    /// Dialog and framing headers are copied or generated by the stack and cannot be supplied in
    /// `headers`. A body requires an application-supplied `Content-Type`.
    pub async fn respond(
        self,
        status: StatusCode,
        reason: impl Into<Bytes>,
        headers: &[Header],
        body: Bytes,
    ) -> Result<()> {
        validate_response(status, headers, &body)?;
        self.response
            .respond(status, reason.into(), headers, body)
            .await
    }
}

#[derive(Debug)]
struct ResponseState {
    claimed: AtomicBool,
    owners: AtomicUsize,
    completed: Notify,
    endpoint: Handle,
    key: TransactionKey,
    request: Request,
}

impl ResponseState {
    fn claim(&self) -> bool {
        self.claimed
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_ok()
    }
}

#[derive(Debug)]
struct ResponseCapability {
    state: Arc<ResponseState>,
}

impl ResponseCapability {
    fn new(endpoint: Handle, key: TransactionKey, request: Request) -> Self {
        let state = Arc::new(ResponseState {
            claimed: AtomicBool::new(false),
            owners: AtomicUsize::new(1),
            completed: Notify::new(),
            endpoint,
            key,
            request,
        });
        let deadline = Arc::clone(&state);
        tokio::spawn(async move {
            // A bound on failure: an abandoned application must not retain a server transaction.
            if tokio::time::timeout(RESPONSE_DEADLINE, deadline.completed.notified())
                .await
                .is_err()
                && deadline.claim()
            {
                send_fallback(&deadline, 504, "Server Time-out").await;
            }
        });
        Self { state }
    }

    async fn respond(
        &self,
        status: StatusCode,
        reason: Bytes,
        headers: &[Header],
        body: Bytes,
    ) -> Result<()> {
        let mut builder = ResponseBuilder::to_request(&self.state.request, status, reason)?;
        for header in headers {
            builder = builder.header(
                header.name().clone(),
                Bytes::copy_from_slice(header.raw_value()),
            )?;
        }
        let response = builder.body(body).build();
        if !self.state.claim() {
            return Err(Error::ApplicationResponseAlreadySent);
        }
        // The final response is committed before I/O. A stream write may fail after sending a
        // prefix—or the complete response—so reopening the capability on transport error would
        // permit a contradictory second final response on the same server transaction. The
        // transport error is returned, but exactly-once ownership remains spent.
        self.state.completed.notify_one();
        let endpoint = self.state.endpoint.clone();
        let key = self.state.key.clone();
        await_committed_send(async move { endpoint.respond(&key, response).await }).await
    }
}

async fn await_committed_send<F>(send: F) -> Result<()>
where
    F: Future<Output = sipx_transport::Result<()>> + Send + 'static,
{
    // There is no await between claiming the capability and spawning this task. Once spawned, the
    // transport operation owns the selected response and survives cancellation of the application
    // future that is only waiting for its result.
    tokio::spawn(send)
        .await
        .map_err(|_| sipx_transport::Error::EndpointClosed)??;
    Ok(())
}

impl Clone for ResponseCapability {
    fn clone(&self) -> Self {
        // Saturation keeps cloning panic-free. Reaching usize::MAX live application handles is
        // outside any addressable process, but the counter remains well-defined even there.
        let _ = self
            .state
            .owners
            .fetch_update(Ordering::AcqRel, Ordering::Acquire, |owners| {
                Some(owners.saturating_add(1))
            });
        Self {
            state: Arc::clone(&self.state),
        }
    }
}

impl Drop for ResponseCapability {
    fn drop(&mut self) {
        let was_last = self
            .state
            .owners
            .fetch_update(Ordering::AcqRel, Ordering::Acquire, |owners| {
                Some(owners.saturating_sub(1))
            })
            .is_ok_and(|owners| owners == 1);
        if !was_last {
            return;
        }
        let Ok(runtime) = tokio::runtime::Handle::try_current() else {
            return;
        };
        if !self.state.claim() {
            return;
        }
        self.state.completed.notify_one();
        let state = Arc::clone(&self.state);
        runtime.spawn(async move {
            send_fallback(&state, 500, "Server Internal Error").await;
        });
    }
}

async fn send_fallback(state: &ResponseState, status: u16, reason: &'static str) {
    let Some(status) = StatusCode::new(status) else {
        return;
    };
    let Ok(builder) = ResponseBuilder::to_request(&state.request, status, reason) else {
        return;
    };
    // discard: the capability is already being abandoned; the transport records an unsent
    // response, and there is no remaining owner to receive this error.
    let _ = state.endpoint.respond(&state.key, builder.build()).await;
}

pub(crate) fn application_owned(method: &Method, admitted: &[Bytes]) -> bool {
    match method {
        Method::Info | Method::Message => true,
        Method::Other(token) => {
            matches!(Method::parse(token), Method::Other(_))
                && admitted.iter().any(|known| known == token)
        }
        _ => false,
    }
}

pub(crate) fn validate_method_for_admission(method: &Method) -> Result<Bytes> {
    match method {
        Method::Other(token) => match Method::parse(token) {
            Method::Other(_) => Ok(token.clone()),
            known => Err(Error::StackOwnedDialogMethod(known)),
        },
        _ => Err(Error::StackOwnedDialogMethod(method.clone())),
    }
}

pub(crate) fn validate_request_parts(headers: &[Header], body: &[u8]) -> Result<()> {
    if body.len() > MAX_APPLICATION_BODY {
        return Err(Error::ApplicationBodyTooLarge {
            actual: body.len(),
            limit: MAX_APPLICATION_BODY,
        });
    }
    for header in headers {
        if protected_header(header.name()) {
            return Err(Error::ProtectedApplicationHeader(header.name().clone()));
        }
    }
    if !body.is_empty()
        && !headers
            .iter()
            .any(|header| header.name() == &HeaderName::ContentType)
    {
        return Err(Error::ApplicationContentTypeRequired);
    }
    Ok(())
}

fn validate_response(status: StatusCode, headers: &[Header], body: &[u8]) -> Result<()> {
    if !status.is_final() {
        return Err(Error::ApplicationFinalResponseRequired(status.code()));
    }
    validate_request_parts(headers, body)
}

fn protected_header(name: &HeaderName) -> bool {
    matches!(
        name,
        HeaderName::Via
            | HeaderName::Route
            | HeaderName::RecordRoute
            | HeaderName::From
            | HeaderName::To
            | HeaderName::CallId
            | HeaderName::CSeq
            | HeaderName::MaxForwards
            | HeaderName::ContentLength
            | HeaderName::Authorization
            | HeaderName::ProxyAuthorization
    )
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]
mod tests {
    use std::sync::Arc;

    use tokio::sync::{Notify, oneshot};

    use super::*;

    #[test]
    fn only_info_message_and_admitted_private_tokens_are_application_owned() {
        let private = Bytes::from_static(b"PRIVATE");
        let admitted = [private.clone()];
        assert!(application_owned(&Method::Info, &admitted));
        assert!(application_owned(&Method::Message, &admitted));
        assert!(application_owned(&Method::Other(private), &admitted));
        assert!(!application_owned(
            &Method::Other(Bytes::from_static(b"private")),
            &admitted
        ));
        for method in [
            Method::Options,
            Method::Bye,
            Method::Invite,
            Method::Update,
            Method::Refer,
            Method::Notify,
        ] {
            assert!(!application_owned(&method, &admitted), "{method}");
        }
    }

    #[test]
    fn canonical_known_tokens_cannot_be_admitted_as_other_methods() {
        for (token, known) in [
            (Bytes::from_static(b"BYE"), Method::Bye),
            (Bytes::from_static(b"INVITE"), Method::Invite),
        ] {
            let alias = Method::Other(token.clone());
            assert!(matches!(
                validate_method_for_admission(&alias),
                Err(Error::StackOwnedDialogMethod(method)) if method == known
            ));
            assert!(!application_owned(&alias, &[token]));
        }
    }

    #[tokio::test]
    async fn a_committed_send_survives_cancellation_of_its_waiter() {
        let started = Arc::new(Notify::new());
        let release = Arc::new(Notify::new());
        let (completed, completion) = oneshot::channel();
        let send_started = Arc::clone(&started);
        let send_release = Arc::clone(&release);

        let waiter = tokio::spawn(await_committed_send(async move {
            send_started.notify_one();
            send_release.notified().await;
            let _ = completed.send(());
            Ok(())
        }));
        started.notified().await;
        waiter.abort();
        let cancelled = waiter
            .await
            .expect_err("the application waiter was cancelled");
        assert!(cancelled.is_cancelled());

        release.notify_one();
        tokio::time::timeout(Duration::from_secs(1), completion)
            .await
            .expect("a bound on failure waiting for the owned send")
            .expect("the owned send completes after waiter cancellation");
    }

    #[test]
    fn protected_headers_are_rejected_before_a_request_can_be_sent() {
        let header = Header::build(HeaderName::CSeq, "99 MESSAGE").expect("valid header syntax");
        assert!(matches!(
            validate_request_parts(&[header], &[]),
            Err(Error::ProtectedApplicationHeader(HeaderName::CSeq))
        ));
    }

    #[test]
    fn body_limit_and_content_type_are_checked_without_partial_send() {
        assert!(matches!(
            validate_request_parts(&[], b"hello"),
            Err(Error::ApplicationContentTypeRequired)
        ));
        let content_type =
            Header::build(HeaderName::ContentType, "text/plain").expect("valid header syntax");
        let oversized = vec![0; MAX_APPLICATION_BODY + 1];
        assert!(matches!(
            validate_request_parts(&[content_type], &oversized),
            Err(Error::ApplicationBodyTooLarge { .. })
        ));
    }
}
