//! Embed the RFC torture corpora so they can be replayed on a target with no filesystem.
//!
//! `docs/specs/browser-sdk.md` §8.1 requires `S-41` to run the RFC 4475 and RFC 5118 corpora
//! against the **WASM build** with native-identical outcomes. `wasm32-unknown-unknown` has no
//! filesystem and `sipx-testkit` — which owns these fixtures — reaches tokio and a socket, so
//! neither reading them at runtime nor depending on the testkit is available here.
//!
//! What is available is `include_bytes!`, which is how the testkit itself embeds them. This script
//! only enumerates the directory; the bytes stay where their importer put them, and nothing is
//! copied. `scripts/import-rfc4475-corpus.sh --check` remains the single source of their
//! provenance.

// A build script is build tooling, not production code, and the same reasoning `AGENTS.md`
// applies to test modules applies here: a build that cannot find the corpus it is supposed to
// embed should fail loudly and immediately, not emit an empty list and let a green test suite
// claim the torture corpora ran.
#![allow(clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let corpus = manifest.join("..").join("sipx-testkit").join("corpus");

    let mut generated = String::from(
        "// Generated by build.rs from crates/sipx-testkit/corpus. Do not edit.\n\
         // Included into a private module of a test binary, so `pub` here reaches nobody. The\n\
         // workspace's `unreachable_pub` lint is right about that and has nothing to offer\n\
         // instead: an `include!` body cannot carry an inner attribute, and `pub(crate)` would\n\
         // not name the enclosing module either.\n\
         #[allow(unreachable_pub)]\n\
         pub static CASES: &[(&str, &[u8])] = &[\n",
    );
    let mut count = 0usize;

    for suite in ["rfc4475", "rfc5118"] {
        let directory = corpus.join(suite);
        println!("cargo:rerun-if-changed={}", directory.display());
        let mut names = BTreeSet::new();
        let entries = std::fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()));
        for entry in entries {
            let entry = entry.expect("a readable directory entry");
            let path = entry.path();
            if !path.is_file() || is_documentation(&path) {
                continue;
            }
            let name = path
                .file_name()
                .and_then(|name| name.to_str())
                .expect("corpus file names are UTF-8")
                .to_owned();
            names.insert(name);
        }
        assert!(
            !names.is_empty(),
            "no corpus files under {}",
            directory.display()
        );
        for name in names {
            let path = directory.join(&name);
            println!("cargo:rerun-if-changed={}", path.display());
            let _ = writeln!(
                generated,
                "    ({:?}, include_bytes!({:?})),",
                format!("{suite}/{name}"),
                path.display().to_string()
            );
            count += 1;
        }
    }

    let _ = writeln!(generated, "];");
    let _ = writeln!(
        generated,
        "#[allow(unreachable_pub)]\npub const CASE_COUNT: usize = {count};"
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join("corpus.rs");
    std::fs::write(&out, generated)
        .unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));
}

/// The corpora carry a `README.md` explaining their provenance; it is not a SIP message.
fn is_documentation(path: &Path) -> bool {
    path.extension().is_some_and(|extension| extension == "md")
}
