#!/usr/bin/env python3
"""Keep every generated report reachable from `docs/README.md`, and derive the set from the tree.

This repository answers questions with generated evidence rather than assertions:
`docs/coverage.md`, `docs/comparison.md`, `docs/compliance.md` and `docs/maturity.md`. Until
`X-117` every one of them was reachable only by already knowing its filename — `X-66` shipped the
newest of the four and reported it as *consistent, and consistently undiscoverable*.

**The set is discovered, not listed.** A page under `docs/` is a generated report when it says so
in its own first lines, in the `Generated by scripts/…` sentence its generator already writes.
That is the whole rule, and it is why this file fixes the class rather than the four instances: a
fifth report is discovered on the commit that adds it, and the check is red until it has an entry
and a link. A hand-typed list of four links would be right today and silent then, which is the
same defect one release later.

**What cannot be discovered is written down once, next to the check that requires it.** Two
sentences per report — what it measures, and what it deliberately does not — are judgement, not
data, and no script can derive them from the page. They live in `ENTRIES` below for the reason
`AGENTS.md` gives for `COMPARISON_SCOPE` living inside `check-provenance.sh`: adding one is then a
reviewable diff rather than a re-reading of a paragraph. Everything mechanical around them *is*
derived — the link, the report's own title, the generator that writes it, and whether the public
site republishes its body — so the only thing an author of a new report has to supply is the
judgement.

**Why the non-claim is mandatory.** `docs/coverage.md` opens with *"What this is not"* and
`docs/maturity.md` closes with *"What this cannot see"*, because both are read by people looking
for a quality claim that neither makes. An index that lists them by name alone hands a reader the
same trap with a shorter walk to it. So an entry that cannot say what its report refuses to claim
is not accepted, and the check that rejects it is this one.

**Why `docs/README.md` and not the site.** `docs/` is the internal contributor tree and is
deliberately not published; two of the four reports have public renderings already, inlined into
`website/docs/reference/` by `scripts/sync-website.py` and indexed by the site's own sidebar. The
other two are internal by design — release readiness for an unreleased project, and a coverage
number nothing gates on. The page a reader of this repository arrives at is `docs/README.md`, so
that is where the four become findable, and each entry says which of them the site also carries.

Usage:
    ./scripts/check-report-index.py            # regenerate the region in docs/README.md
    ./scripts/check-report-index.py --check    # verify it, write nothing (the gate's mode)
    ./scripts/check-report-index.py --root DIR # a tree assembled by a test
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import textwrap
from typing import NamedTuple

ROOT = pathlib.Path(__file__).resolve().parent.parent

#: The page a reader of this repository arrives at, and the region of it this script owns.
INDEX = pathlib.PurePath("docs/README.md")
BEGIN = "<!-- BEGIN reports -->"
END = "<!-- END reports -->"

#: Where reports live. Top level only: `docs/coverage/` and `docs/comparison/` hold the *inputs*
#: a report is generated from, and a data file is not a page to send a reader to.
REPORTS = pathlib.PurePath("docs")

#: The published half, scanned to find out which reports the site republishes. The marker is
#: `sync-website.py`'s own, so this reads the site's arrangement rather than restating it.
SITE = pathlib.PurePath("website/docs")
PUBLISHED = "<!-- BEGIN generated:{stem} -->"

#: How far into a page the generated-by sentence must appear. All four write it on line 3; the
#: slack is for a report that grows a badge or a front-matter block above it. Keeping it to the
#: head is what stops a page that merely *mentions* a generator from being treated as one.
HEAD_LINES = 10

#: Both spellings the generators use: an HTML comment (`comparison`, `compliance`) and ordinary
#: prose with the path in backticks (`coverage`, `maturity`). The path is required — a sentence
#: that cannot name its generator cannot be checked against one.
GENERATED_BY = re.compile(r"[Gg]enerated by\s+`?(?P<generator>scripts/[\w.-]+\.(?:py|sh))`?")
TITLE = re.compile(r"^#\s+(?P<title>\S.*?)\s*$", re.MULTILINE)

#: Wrapping width for the rendered region, matching the prose around it in `docs/`.
WIDTH = 92


class Entry(NamedTuple):
    """The two sentences no script can derive from a page."""

    #: What the report measures — the reason to open it.
    measures: str
    #: What it deliberately does not claim, carried from the report's own words. A reader who
    #: has to open the page to learn this has already paid the cost the index exists to save,
    #: so a paraphrase that sounds stronger than the source is the failure mode to avoid.
    deliberately_not: str


#: One entry per generated report. A report with no entry here fails the check by name, which is
#: the story's Acceptance: the fifth report cannot land undiscoverable.
ENTRIES = {
    "comparison.md": Entry(
        measures=(
            "what choosing sipx wins and what it costs against the stacks a reader is actually "
            "weighing it against, one confidence tier per cell, plus a leaf-level endpoint "
            "capability ledger and a signalling-load ladder."
        ),
        deliberately_not=(
            "the comparison is asymmetric: sipx's own column is computed from this repository, "
            "and every other column is somebody reading someone else's code. The capability "
            "ledger is a finite discovery gate, not a score, and a stack that was not evaluated "
            "on a question says so in its own row."
        ),
    ),
    "compliance.md": Entry(
        measures=(
            "what sipx implements, what it only parses and what it has not started, per RFC and "
            "per role, generated from `docs/rfc/registry.toml` and held against the parser and "
            "the files each entry cites."
        ),
        deliberately_not=(
            "it cannot check that behaviour is *correct*; the tests do that, and each entry "
            "points at them. The list is bounded on purpose and is not every SIP-related RFC. "
            "What it stops is this table drifting away from the code."
        ),
    ),
    "coverage.md": Entry(
        measures=(
            "which lines, branches and functions the suite executes, per crate and "
            "workspace-wide, as arithmetic over recorded counts rather than a transcribed figure. "
            "It names the commit it was measured at, what the measurement leaves out, and the "
            "code no test reaches at all."
        ),
        deliberately_not=(
            "**no threshold gates the build on any number on it**, and a drop fails nothing. It "
            "measures what the suite executes, not whether executing it proved anything."
        ),
    ),
    "maturity.md": Entry(
        measures=(
            "distance to the release predicates, RFC coverage per layer, open work per pillar and "
            "filed-versus-closed per day, generated from roadmap predicates, story frontmatter "
            "and git."
        ),
        deliberately_not=(
            "it does not turn RFC coverage into a weighted release score, and nothing in it "
            "measures whether the tests are good, only that they pass. Some predicates are "
            "attested rather than computed, and it names which."
        ),
    ),
}


class Report(NamedTuple):
    """A generated page under `docs/`, and everything about it that is read off the tree."""

    #: Path relative to the repository root.
    path: pathlib.PurePath
    #: The page's own `# ` heading, so a renamed report renames its own link.
    title: str
    #: The script named in its generated-by sentence, checked to exist.
    generator: pathlib.PurePath
    #: The public page whose body is generated from it, or `None` when it is internal.
    published: pathlib.PurePath | None


def published_in(root: pathlib.Path, stem: str) -> pathlib.PurePath | None:
    """The site page that republishes this report's body, if the site has one.

    Read from `sync-website.py`'s region marker rather than from a list here: the site decides
    what it publishes, and a second list would be one more thing to keep true.
    """
    site = root / SITE
    if not site.is_dir():
        return None
    marker = PUBLISHED.format(stem=stem)
    for page in sorted(site.rglob("*.md")):
        if marker in page.read_text():
            return page.relative_to(root)
    return None


def discover(root: pathlib.Path) -> list[Report]:
    """Every generated report under `docs/`, found by what each page says about itself."""
    found = []
    for path in sorted((root / REPORTS).glob("*.md")):
        if path.name == INDEX.name:
            continue
        text = path.read_text()
        head = "\n".join(text.splitlines()[:HEAD_LINES])
        marker = GENERATED_BY.search(head)
        if marker is None:
            continue
        title = TITLE.search(text)
        found.append(
            Report(
                path=path.relative_to(root),
                title="" if title is None else title.group("title"),
                generator=pathlib.PurePath(marker.group("generator")),
                published=published_in(root, path.stem),
            )
        )
    return found


def provenance(report: Report) -> str:
    """Where the page comes from and where else it is read — both derived from the tree."""
    if report.published is None:
        return f"Generated by `{report.generator}`; internal to this repository."
    label = report.published.relative_to(SITE).with_suffix("")
    site = pathlib.PurePath("..") / report.published
    return (
        f"Generated by `{report.generator}`; its body is also published on the site as "
        f"[{label}]({site})."
    )


def render(reports: list[Report]) -> str:
    """The region body: one paragraph per report, wrapped so the source diffs a line at a time."""
    bullets = []
    for report in reports:
        entry = ENTRIES[report.path.name]
        bullets.append(
            textwrap.fill(
                f"**[{report.title}]({report.path.name})** — {entry.measures} "
                f"**Deliberately not** — {entry.deliberately_not} {provenance(report)}",
                width=WIDTH,
                initial_indent="- ",
                subsequent_indent="  ",
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "\n" + "\n\n".join(bullets) + "\n"


def analyse(root: pathlib.Path) -> tuple[list[Report], list[str]]:
    """The reports, and everything wrong with them that is not the index region itself."""
    reports = discover(root)
    problems = []
    for report in reports:
        if not report.title:
            problems.append(f"{report.path} has no `# ` heading to link by")
        if not (root / report.generator).exists():
            problems.append(
                f"{report.path} says it is generated by {report.generator}, which does not exist"
            )
        if report.path.name not in ENTRIES:
            problems.append(
                f"{report.path} is a generated report with no index entry. Add one to ENTRIES in "
                f"{pathlib.PurePath(__file__).name}, saying what it measures and what it "
                f"deliberately does not, then run ./scripts/check-report-index.py"
            )
    for name in sorted(ENTRIES):
        if not any(report.path.name == name for report in reports):
            problems.append(
                f"ENTRIES describes docs/{name}, which is not a generated report under "
                f"{REPORTS}/ — remove the entry, or restore the page it indexes"
            )
    return reports, problems


def split(text: str) -> tuple[str, str, str]:
    """The index around the region this script owns. Raises `ValueError` when it is absent."""
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    if end < start:
        raise ValueError("region markers are out of order")
    return text[:start], text[start:end], text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help=f"verify the region in {INDEX} describes the tree, and write nothing",
    )
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=ROOT,
        help="the repository to read (default: the one this script lives in)",
    )
    args = parser.parse_args()
    root = args.root.resolve()

    reports, problems = analyse(root)
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1

    index = root / INDEX
    try:
        before, current, after = split(index.read_text())
    except (ValueError, FileNotFoundError):
        print(
            f"{INDEX} has no `{BEGIN}` … `{END}` region for the generated reports to be listed in",
            file=sys.stderr,
        )
        return 1

    body = render(reports)
    if args.check:
        if current != body:
            print(
                f"{INDEX} is out of date; run ./scripts/check-report-index.py",
                file=sys.stderr,
            )
            return 1
        return 0

    index.write_text(before + body + after)
    return 0


if __name__ == "__main__":
    sys.exit(main())
