#!/usr/bin/env python3
"""Project the kernel's actual Rust wire declarations; --check never writes."""

from __future__ import annotations
import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def block(text, start):
    start = text.index("{", start)
    depth = 0
    quoted = False
    escaped = False
    for i in range(start, len(text)):
        c = text[i]
        if quoted:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                quoted = False
            continue
        if c == '"':
            quoted = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
    raise ValueError("unclosed wire declaration")


def split(text):
    result = []
    start = 0
    depth = 0
    for i, c in enumerate(text):
        if c in "<{(":
            depth += 1
        if c in ">})":
            depth -= 1
        if c == "," and depth == 0:
            result.append(text[start:i].strip())
            start = i + 1
    if text[start:].strip():
        result.append(text[start:].strip())
    return result


def fields(text, separator=None):
    out = {}
    for value in split(text):
        name, ty = value.split(":", 1)
        if separator:
            ty = ty.split(separator, 1)[0]
        out[name.strip()] = ty.strip()
    return out


def ts(ty):
    if ty.startswith("Option<"):
        return ts(ty[7:-1]) + " | undefined"
    if ty.startswith("Vec<"):
        return ts(ty[4:-1]) + "[]"
    if ty in ("u8", "u16", "u32", "u64", "i32"):
        return "number"
    if ty in ("String", "&'static str"):
        return "string"
    if ty == "bool":
        return "boolean"
    return ty


def members(values):
    return "; ".join(
        name
        + ("?" if ty.startswith("Option<") else "")
        + ": "
        + ts(ty).replace(" | undefined", "")
        for name, ty in values.items()
    )


def generate(root):
    source = root / "crates/sipx-wasm/src/contract.rs"
    text = source.read_text()

    def section(name):
        a = text.index("macro_rules! " + name)
        a = text.index("$emit! ", a)
        return block(text, a)[0]

    strings = {
        name: re.findall(r'=> "([^"]+)"', body)
        for name, body in re.findall(
            r"(\w+)\s*\{([^{}]*)\};", block(text, text.index("wire_strings! {"))[0]
        )
    }
    commands = {
        wire: fields(body, "=>")
        for _, wire, body in re.findall(
            r'(\w+)\("([^"]+)"\)\s*\{([^{}]*)\};', section("browser_commands")
        )
    }
    objects = {
        name: fields(body)
        for name, body in re.findall(
            r"(\w+)\s*\{([^{}]*)\};", section("browser_objects")
        )
    }
    events = {}
    remaining = section("browser_events")
    pos = 0
    while match := re.search(r'(\w+)\("([^"]+)"\)\s*\{', remaining[pos:]):
        a = pos + match.start()
        _, end = block(remaining, a)
        wire_fields, end = block(remaining, end)
        events[match[2]] = fields(wire_fields, "=")
        pos = end
    errors = {
        name: {"code": int(code), "token": token}
        for name, code, token in re.findall(
            r'(\w+) = (-\d+) => "([^"]+)";', section("browser_errors")
        )
    }
    abi = {
        name: {"parameters": fields(args), "result": result or "void"}
        for name, args, result in re.findall(
            r'pub extern "C" fn (\w+)\(([^)]*)\)(?: -> (\w+))?', section("browser_abi")
        )
    }
    version = int(
        re.search(
            r"pub const ABI_VERSION: i32 = (\d+);",
            (root / "crates/sipx-wasm/src/abi.rs").read_text(),
        )[1]
    )
    if not all((commands, events, errors, abi, objects, strings)):
        raise ValueError("empty contract section")
    manifest = {
        "abiVersion": version,
        "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "abi": abi,
        "commands": commands,
        "events": events,
        "objects": objects,
        "strings": strings,
        "errors": errors,
    }
    pre = "// Generated by scripts/generate-browser.py from the consumed Rust wire declaration. Do not edit.\n"
    js = (
        pre
        + "export const contract = Object.freeze("
        + json.dumps(manifest, indent=2)
        + ");\n"
    )
    js += """export function bindABI(exports) {
  if (typeof exports.sipx_abi_version !== "function" || exports.sipx_abi_version() !== contract.abiVersion) throw new Error("ABI version mismatch");
  const bound = { memory: exports.memory };
  for (const [name, signature] of Object.entries(contract.abi)) {
    const fn = exports[name];
    if (typeof fn !== "function" || fn.length !== Object.keys(signature.parameters).length) throw new Error("ABI signature mismatch");
    bound[name] = (...args) => fn(...args);
  }
  return Object.freeze(bound);
}
export function command(verb, id, fields = {}) {
  if (!Object.hasOwn(contract.commands, verb)) throw new TypeError("unknown command");
  return {v:contract.abiVersion, cmd:verb, id, ...fields};
}
"""
    decl = pre + "export interface ABI { memory: WebAssembly.Memory;\n"
    for name, v in abi.items():
        args = ", ".join(
            k + ": " + ("bigint" if ty == "u64" else "number")
            for k, ty in v["parameters"].items()
        )
        ret = (
            "bigint"
            if v["result"] == "u64"
            else ("void" if v["result"] == "void" else "number")
        )
        decl += f"  {name}({args}): {ret};\n"
    decl += "}\n"
    for name, values in strings.items():
        decl += (
            f"export type {name} = " + " | ".join(json.dumps(v) for v in values) + ";\n"
        )
    for name, values in objects.items():
        decl += f"export interface {name} {{ {members(values)} }}\n"
    decl += (
        "export type Command =\n"
        + "\n".join(
            "  | { v: 1; cmd: "
            + json.dumps(name)
            + "; id: number; "
            + members(values)
            + " }"
            for name, values in commands.items()
        )
        + ";\n"
    )
    decl += (
        "export type KernelEvent =\n"
        + "\n".join(
            "  | { v: 1; evt: " + json.dumps(name) + "; " + members(values) + " }"
            for name, values in events.items()
        )
        + ";\n"
    )
    decl += (
        "export type AbiErrorCode = "
        + " | ".join(str(v["code"]) for v in errors.values())
        + ";\n"
    )
    return {
        "browser/generated/contract.json": json.dumps(manifest, indent=2) + "\n",
        "browser/generated/abi.mjs": js,
        "browser/generated/wire.d.ts": decl,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=pathlib.Path, default=ROOT)
    args = parser.parse_args()
    bad = []
    for rel, text in generate(args.root).items():
        p = args.root / rel
        if args.check:
            if not p.is_file() or p.read_text() != text:
                bad.append(rel)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
    if bad:
        print("browser generation drift: " + ", ".join(bad), file=sys.stderr)
        return 1
    print("browser generation: ABI, command, event and error declarations agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
