#!/usr/bin/env python3
"""Render docs/compliance.md from docs/rfc/registry.toml, and check that it is not lying.

A compliance table nobody can verify is marketing. This does two things a hand-written table
cannot: it regenerates the document so it cannot drift from its source, and with `--check` it
holds the source against the code — every header and method an entry names must actually be
known to the parser, and every file it cites must exist.

What it deliberately does *not* claim to verify is behaviour. No script can read
`crates/sipx-sip/src/transaction/client.rs` and decide whether Timer A is right; the tests do
that. What it can do is stop an entry claiming syntax support for a header the code has never
heard of, which is the failure mode a table like this actually has.
"""

import argparse
import pathlib
import re
import sys
import tomllib
from collections import Counter, defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs" / "rfc" / "registry.toml"
REPORT = ROOT / "docs" / "compliance.md"
NAMES = ROOT / "crates" / "sipx-sip" / "src" / "name.rs"
METHODS = ROOT / "crates" / "sipx-sip" / "src" / "message.rs"

STATUS_ORDER = ["implemented", "partial", "syntax", "none", "n/a"]
STATUS_LABEL = {
    "implemented": "✅ implemented",
    "partial": "🟡 partial",
    "syntax": "🔤 syntax only",
    "none": "⬜ not started",
    "n/a": "— superseded",
}
LAYER_ORDER = ["wire", "transport", "core", "security", "media", "services"]
LAYER_TITLE = {
    "wire": "Wire — can the bytes be represented at all?",
    "transport": "Transport — how a message travels, and how the far end is found",
    "core": "Core — transactions, dialogs, negotiation",
    "security": "Security — transport security, authentication, identity",
    "media": "Media — describing it, carrying it, encoding it",
    "services": "Services — what is built on top",
}


def known_headers() -> set[str]:
    """Header variants the parser knows, read from the name table."""
    return set(re.findall(r"^\s+(\w+)\s+=> \"", NAMES.read_text(), re.M))


def known_methods() -> set[str]:
    """Method tokens the parser knows, read from the wire spellings."""
    return {m.upper() for m in re.findall(r'b"([A-Z]+)" =>', METHODS.read_text())}


def check(entries) -> list[str]:
    """Every claim that the code does not back up."""
    headers, methods = known_headers(), known_methods()
    problems = []

    for entry in entries:
        where = f"RFC {entry['number']}"

        if entry["status"] not in STATUS_LABEL:
            problems.append(f"{where}: unknown status {entry['status']!r}")
        if entry["layer"] not in LAYER_TITLE:
            problems.append(f"{where}: unknown layer {entry['layer']!r}")

        for header in entry.get("headers", []):
            if header not in headers:
                problems.append(
                    f"{where} names header {header!r}, which the parser does not know"
                )
        for method in entry.get("methods", []):
            if method not in methods:
                problems.append(
                    f"{where} names method {method!r}, which the parser does not know"
                )
        for path in entry.get("evidence", []):
            if not (ROOT / path).exists():
                problems.append(f"{where} cites {path}, which does not exist")

        # An entry that claims to be implemented and points at nothing is an assertion.
        if entry["status"] in {"implemented", "partial"} and not entry.get("evidence"):
            problems.append(f"{where} claims {entry['status']} with no evidence cited")

    numbers = [e["number"] for e in entries]
    for number, count in Counter(numbers).items():
        if count > 1:
            problems.append(f"RFC {number} appears {count} times")

    return problems


def render(entries) -> str:
    by_layer = defaultdict(list)
    for entry in entries:
        by_layer[entry["layer"]].append(entry)

    counts = Counter(e["status"] for e in entries)
    tracked = len(entries)

    out = [
        "# RFC compliance",
        "",
        "<!-- Generated by scripts/rfc-report.py from docs/rfc/registry.toml. Do not edit. -->",
        "",
        "What sipx implements, what it only parses, and what it has not started — measured",
        "rather than asserted. `scripts/rfc-report.py --check` runs in CI and fails the build if",
        "an entry names a header the parser does not know, or cites a file that does not exist.",
        "",
        "It cannot check that behaviour is *correct*; the tests do that, and each entry points at",
        "them. What it can do is stop this table drifting away from the code, which is the way a",
        "compliance document usually becomes untrue.",
        "",
        "## Where it stands",
        "",
        f"**{tracked} RFCs tracked.**",
        "",
        "| | Meaning | Count |",
        "|---|---|---|",
    ]
    meanings = {
        "implemented": "Behaviour present and tested for the roles listed",
        "partial": "Some of the normative behaviour; the note says which part is missing",
        "syntax": "The parser represents it; nothing acts on it",
        "none": "Tracked as a target, not started",
        "n/a": "Obsoleted by a later RFC that is tracked instead",
    }
    for status in STATUS_ORDER:
        out.append(f"| {STATUS_LABEL[status]} | {meanings[status]} | {counts.get(status, 0)} |")

    out += [
        "",
        "The list is bounded on purpose: it is what sipx already touches plus what it has decided",
        "to aim at. It is not every SIP-related RFC and it never will be — some update or obsolete",
        "others, some define alternatives to each other, and some belong to trust domains sipx does",
        "not operate in. The order to add them in is in the",
        "[RFC roadmap](rfc-roadmap.md).",
        "",
        "**Roles.** sipx is a user agent. Where an RFC defines proxy or registrar behaviour, that",
        "behaviour is not implemented even when the UA half is — the `Roles` column says which.",
        "",
    ]

    for layer in LAYER_ORDER:
        rows = by_layer.get(layer, [])
        if not rows:
            continue
        rows.sort(key=lambda e: (STATUS_ORDER.index(e["status"]), e["number"]))
        out += [f"## {LAYER_TITLE[layer]}", "", "| RFC | Title | Status | Roles | Notes |", "|---|---|---|---|---|"]
        for entry in rows:
            roles = ", ".join(entry.get("roles", [])) or "—"
            link = f"[{entry['number']}](https://www.rfc-editor.org/rfc/rfc{entry['number']})"
            note = entry.get("note", "").replace("|", "\\|")
            out.append(
                f"| {link} | {entry['title']} | {STATUS_LABEL[entry['status']]} | {roles} | {note} |"
            )
        out.append("")

    out += [
        "## How to read a status",
        "",
        "**Syntax only is not a half-measure, it is a different thing.** sipx parses `RAck` and",
        "`RSeq` and does nothing with them: a message carrying them survives the wire and is",
        "forwarded intact, and no PRACK is ever sent. That is worth recording separately, because",
        "\"we support RFC 3262\" would be false and \"we reject it\" would also be false.",
        "",
        "**Partial always says what is missing.** An entry that cannot name the gap should be",
        "`none` until somebody works out what it is.",
        "",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify claims and that the report is current")
    args = parser.parse_args()

    entries = tomllib.loads(REGISTRY.read_text())["rfc"]
    problems = check(entries)
    rendered = render(entries)

    if args.check:
        if REPORT.exists() and REPORT.read_text() != rendered:
            problems.append(
                f"{REPORT.relative_to(ROOT)} is out of date; run scripts/rfc-report.py"
            )
        if problems:
            print("RFC compliance claims that the code does not back up:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            return 1
        print(f"rfc compliance: {len(entries)} RFCs, every claim backed")
        return 0

    if problems:
        for problem in problems:
            print(f"warning: {problem}", file=sys.stderr)
    REPORT.write_text(rendered)
    print(f"wrote {REPORT.relative_to(ROOT)}: {len(entries)} RFCs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
