//! Certificate verification, against a fixture CA.
//!
//! Vector numbers refer to `docs/specs/sip-tls.md` §6. Every certificate here is generated by
//! the test, so nothing depends on a public CA, on a clock beyond the test's control, or on
//! anyone else's expiry date.
//!
//! What these check is not that TLS works — the library's own tests do that — but that sipx
//! asks it the right question. A handshake that succeeds against the wrong certificate is
//! indistinguishable from one that succeeds against the right one, until it matters.

#![cfg(feature = "tls")]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::time::Duration;

use sipx_testkit::certs::{Ca, dns};
use sipx_transport::tls::{ClientTls, Identity, ServerTls, TrustAnchors, verification_name};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};

/// Run one handshake and report what happened.
///
/// The server presents `cert_pem`; the client verifies against `anchors` and checks the name
/// `expect_name`.
async fn handshake(
    cert_pem: &str,
    key_pem: &str,
    anchors: &TrustAnchors,
    expect_name: &str,
) -> Result<(), String> {
    let identity = Identity::from_pem(cert_pem.as_bytes(), key_pem.as_bytes())
        .map_err(|error| error.to_string())?;
    let server = ServerTls::new(identity).map_err(|error| error.to_string())?;
    let client = ClientTls::new(anchors).map_err(|error| error.to_string())?;

    let listener = TcpListener::bind("127.0.0.1:0").await.expect("binds");
    let addr = listener.local_addr().expect("has an address");

    let acceptor = server.acceptor();
    let accepting = tokio::spawn(async move {
        let Ok((stream, _)) = listener.accept().await else {
            return;
        };
        if let Ok(mut tls) = acceptor.accept(stream).await {
            let _ = tls.write_all(b"hello").await;
            let _ = tls.shutdown().await;
        }
    });

    let name = verification_name(expect_name).map_err(|error| error.to_string())?;
    let stream = TcpStream::connect(addr).await.expect("connects");

    let result = tokio::time::timeout(
        Duration::from_secs(5),
        client.connector().connect(name, stream),
    )
    .await
    .map_err(|_| "handshake timed out".to_owned())?;

    let outcome = match result {
        Ok(mut tls) => {
            let mut buf = [0u8; 5];
            let _ = tls.read_exact(&mut buf).await;
            Ok(())
        }
        Err(error) => Err(error.to_string()),
    };

    accepting.abort();
    outcome
}

fn trusting(ca: &Ca) -> TrustAnchors {
    let mut anchors = TrustAnchors::only();
    anchors.add_pem(ca.pem().as_bytes()).expect("a usable CA");
    anchors
}

/// The baseline: the right certificate, from a trusted CA, for the right host.
#[tokio::test]
async fn a_matching_certificate_from_a_trusted_ca_is_accepted() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("sip.example.com")], "sip.example.com");
    handshake(&cert, &key, &trusting(&ca), "sip.example.com")
        .await
        .expect("the handshake must succeed");
}

/// L1: a certificate nobody vouches for.
#[tokio::test]
async fn a_certificate_from_an_untrusted_ca_is_refused() {
    let ca = Ca::new();
    let other = Ca::new();
    let (cert, key) = ca.issue(&[dns("sip.example.com")], "sip.example.com");

    handshake(&cert, &key, &trusting(&other), "sip.example.com")
        .await
        .expect_err("an unknown issuer must be refused");
}

/// L2, and the failing-first test this story names. A valid certificate for somebody else is
/// the case that matters: the chain is fine, the CA is trusted, and it is still the wrong peer.
#[tokio::test]
async fn a_certificate_for_the_wrong_host_is_refused() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("elsewhere.example.com")], "elsewhere.example.com");

    handshake(&cert, &key, &trusting(&ca), "sip.example.com")
        .await
        .expect_err("a certificate for another host must be refused");
}

/// The spec requires that a failure name *which* check failed: expired, wrong host and unknown
/// issuer are three operational problems with three different fixes, and collapsing them into
/// "handshake failed" costs an engineer an afternoon.
///
/// Asserting the distinction rather than the wording — the wording belongs to the TLS library
/// and will change; that the two are tellable apart is sipx's requirement.
#[tokio::test]
async fn different_verification_failures_are_reported_differently() {
    let ca = Ca::new();
    let other = Ca::new();

    let (good, good_key) = ca.issue(&[dns("sip.example.com")], "sip.example.com");
    let (wrong_host, wrong_host_key) =
        ca.issue(&[dns("elsewhere.example.com")], "elsewhere.example.com");

    let untrusted = handshake(&good, &good_key, &trusting(&other), "sip.example.com")
        .await
        .expect_err("unknown issuer");
    let mismatch = handshake(
        &wrong_host,
        &wrong_host_key,
        &trusting(&ca),
        "sip.example.com",
    )
    .await
    .expect_err("wrong host");

    assert_ne!(
        untrusted, mismatch,
        "an untrusted issuer and a wrong host must not report the same thing"
    );
    for error in [&untrusted, &mismatch] {
        assert!(
            !error.is_empty() && error.len() > "failed".len(),
            "a bare failure says nothing: {error}"
        );
    }
}

/// L4: the case RFC 6125 §6.4.4 exists for. A certificate with a `subjectAltName` that does not
/// match is a failure — the common name is **not** consulted as a second chance. A stack that
/// falls back to the CN here accepts certificates the issuer did not authorise for this name.
#[tokio::test]
async fn a_matching_common_name_does_not_rescue_a_wrong_san() {
    let ca = Ca::new();
    // SAN says elsewhere; CN says the host we want.
    let (cert, key) = ca.issue(&[dns("elsewhere.example.com")], "sip.example.com");

    handshake(&cert, &key, &trusting(&ca), "sip.example.com")
        .await
        .expect_err("the CN must not be consulted when a SAN is present");
}

/// L6: a wildcard covers one leftmost label.
#[tokio::test]
async fn a_wildcard_matches_a_single_label() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("*.example.com")], "*.example.com");

    handshake(&cert, &key, &trusting(&ca), "sip.example.com")
        .await
        .expect("a wildcard covers one label");
}

/// L7: and only one. `*.example.com` is not a licence for the whole tree beneath it.
#[tokio::test]
async fn a_wildcard_does_not_match_two_labels() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("*.example.com")], "*.example.com");

    handshake(&cert, &key, &trusting(&ca), "a.b.example.com")
        .await
        .expect_err("a wildcard must not cover a second label");
}

/// A wildcard does not cover the bare domain either.
#[tokio::test]
async fn a_wildcard_does_not_match_the_bare_domain() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("*.example.com")], "*.example.com");

    handshake(&cert, &key, &trusting(&ca), "example.com")
        .await
        .expect_err("*.example.com is not example.com");
}

/// A certificate carrying several names is normal for a proxy serving many domains, and any
/// one matching is enough.
#[tokio::test]
async fn any_of_several_names_may_match() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(
        &[
            dns("first.example.com"),
            dns("sip.example.com"),
            dns("third.example.com"),
        ],
        "first.example.com",
    );

    for host in ["first.example.com", "sip.example.com", "third.example.com"] {
        handshake(&cert, &key, &trusting(&ca), host)
            .await
            .unwrap_or_else(|error| panic!("{host} should match: {error}"));
    }
    handshake(&cert, &key, &trusting(&ca), "fourth.example.com")
        .await
        .expect_err("a name not on the certificate must still be refused");
}

/// The shape of the escape hatch, asserted. Trusting a fixture CA is an *addition* to the
/// anchors — there is no way to say "accept anything", so a mistake in a test produces a failed
/// handshake rather than a silently accepted one.
#[tokio::test]
async fn there_is_no_way_to_accept_an_unverified_certificate() {
    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("sip.example.com")], "sip.example.com");

    // An empty anchor set refuses at construction rather than accepting everything.
    let error = ClientTls::new(&TrustAnchors::only()).expect_err("no anchors is a config error");
    assert!(error.to_string().contains("no trust anchors"), "{error}");

    // And the system anchors do not vouch for a fixture CA.
    handshake(&cert, &key, &TrustAnchors::system(), "sip.example.com")
        .await
        .expect_err("a private CA must not be trusted by default");
}

/// The point of all of the above: a SIP exchange that actually crosses TLS.
///
/// Verification is on — the client trusts the fixture CA and checks the name — so a handshake
/// that quietly skipped it would still pass this, but the tests above have already established
/// that it cannot.
#[tokio::test]
async fn a_sip_request_and_response_cross_tls() {
    use bytes::Bytes;
    use sipx_sip::build::{RequestBuilder, ResponseBuilder};
    use sipx_sip::{HeaderName, Host, HostName, Method, StatusCode, Uri};
    use sipx_transport::{Config, Target, TransportKind, bind};

    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("localhost")], "localhost");
    let identity = Identity::from_pem(cert.as_bytes(), key.as_bytes()).expect("an identity");
    let server_tls = ServerTls::new(identity).expect("a server");

    // The server listens for TLS on its own port, as RFC 3261 §19.1.2 expects.
    let mut server_config = Config::new("127.0.0.1:0".parse().expect("valid"));
    server_config.tls_server = Some((server_tls, 0));
    let (server, mut server_rx) = bind(server_config).await.expect("binds");

    // The client trusts the fixture CA — an addition to its anchors, not a bypass.
    let client_tls = ClientTls::new(&trusting(&ca)).expect("a client");
    let mut client_config = Config::new("127.0.0.1:0".parse().expect("valid"));
    client_config.tls_client = Some(client_tls);
    let (client, _client_rx) = bind(client_config).await.expect("binds");

    let tls_port = server.tls_addr().expect("a TLS port was bound").port();
    let target = Target::new(
        format!("127.0.0.1:{tls_port}").parse().expect("valid"),
        TransportKind::Tls,
    )
    // The name from the URI, which is what the certificate must be valid for.
    .verifying("localhost");

    let responder = tokio::spawn(async move {
        let incoming = server_rx.recv().await.expect("a request arrives over TLS");
        assert_eq!(incoming.transport, TransportKind::Tls);
        let response = ResponseBuilder::to_request(
            &incoming.request,
            StatusCode::new(200).expect("valid"),
            "OK",
        )
        .expect("builds")
        .build();
        server
            .respond(&incoming.key, response)
            .await
            .expect("responds");
    });

    let uri = Uri::sip(Host::Name(HostName::new("localhost").expect("valid")));
    let options = RequestBuilder::new(Method::Options, uri)
        .header(HeaderName::To, "<sip:callee@localhost>")
        .expect("valid")
        .header(HeaderName::From, "<sip:caller@localhost>;tag=t1")
        .expect("valid")
        .header(
            HeaderName::CallId,
            Bytes::from_static(b"tls-call@localhost"),
        )
        .expect("valid")
        .cseq(1, &Method::Options)
        .expect("valid")
        .max_forwards(70)
        .build();

    let mut responses = client.send(options, target).await.expect("sends");
    let response = tokio::time::timeout(Duration::from_secs(5), responses.final_response())
        .await
        .expect("no timeout")
        .expect("a final response over TLS");
    assert_eq!(response.status.code(), 200);

    responder.await.expect("the responder finishes");
}

/// And the negative: the same exchange with a certificate for the wrong host does not happen at
/// all. The transaction fails rather than falling back to cleartext.
#[tokio::test]
async fn a_wrong_certificate_stops_the_exchange_rather_than_downgrading() {
    use sipx_transport::{Config, Target, TransportKind, bind};

    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("elsewhere.example")], "elsewhere.example");
    let identity = Identity::from_pem(cert.as_bytes(), key.as_bytes()).expect("an identity");
    let server_tls = ServerTls::new(identity).expect("a server");

    let mut server_config = Config::new("127.0.0.1:0".parse().expect("valid"));
    server_config.tls_server = Some((server_tls, 0));
    let (server, mut server_rx) = bind(server_config).await.expect("binds");

    let client_tls = ClientTls::new(&trusting(&ca)).expect("a client");
    let mut client_config = Config::new("127.0.0.1:0".parse().expect("valid"));
    client_config.tls_client = Some(client_tls);
    client_config.timers = sipx_sip::Timers {
        t1: Duration::from_millis(10),
        t2: Duration::from_millis(40),
        t4: Duration::from_millis(40),
    };
    let (client, _rx) = bind(client_config).await.expect("binds");

    let tls_port = server.tls_addr().expect("a TLS port").port();
    let target = Target::new(
        format!("127.0.0.1:{tls_port}").parse().expect("valid"),
        TransportKind::Tls,
    )
    .verifying("localhost");

    let request = {
        use bytes::Bytes;
        use sipx_sip::build::RequestBuilder;
        use sipx_sip::{HeaderName, Host, HostName, Method, Uri};
        RequestBuilder::new(
            Method::Options,
            Uri::sip(Host::Name(HostName::new("localhost").expect("valid"))),
        )
        .header(HeaderName::To, "<sip:callee@localhost>")
        .expect("valid")
        .header(HeaderName::From, "<sip:caller@localhost>;tag=t1")
        .expect("valid")
        .header(HeaderName::CallId, Bytes::from_static(b"bad-tls@localhost"))
        .expect("valid")
        .cseq(1, &Method::Options)
        .expect("valid")
        .max_forwards(70)
        .build()
    };

    let mut responses = client.send(request, target).await.expect("queues");
    let ended = tokio::time::timeout(Duration::from_secs(5), async {
        while responses.next().await.is_some() {}
    })
    .await;
    assert!(ended.is_ok(), "the transaction must end rather than hang");

    // And nothing ever reached the application on the far side.
    assert!(
        server_rx.try_recv().is_err(),
        "a request must not cross a connection that failed verification"
    );
}

/// L10. Two hosts served from one address are two connections, not one reused.
///
/// `docs/specs/sip-tls.md` §5. Handing traffic for `a.example.com` to a connection
/// authenticated as `b.example.com` throws away the verification that was just performed —
/// and a proxy serving many domains from one address is the ordinary case, not a contrived one.
#[tokio::test]
async fn two_names_on_one_address_are_two_connections() {
    use sipx_transport::{ConnectionKey, Pool, PoolConfig, TransportKind};

    let listener = TcpListener::bind("127.0.0.1:0").await.expect("binds");
    let addr = listener.local_addr().expect("has an address");
    let accepting = tokio::spawn(async move { listener.accept().await.expect("accepts") });
    let _client = TcpStream::connect(addr).await.expect("connects");
    let (_stream, peer) = accepting.await.expect("accepted");

    let (events, _rx) = tokio::sync::mpsc::channel(64);
    let pool = Pool::new(PoolConfig::default(), sipx_sip::Limits::stream(), events);

    let one = ConnectionKey {
        peer,
        transport: TransportKind::Tls,
        identity: Some(std::sync::Arc::from("a.example.com")),
    };
    let other = ConnectionKey {
        peer,
        transport: TransportKind::Tls,
        identity: Some(std::sync::Arc::from("b.example.com")),
    };

    assert_ne!(
        one, other,
        "the verified name is part of what a connection is"
    );
    assert!(!pool.holds(&one) && !pool.holds(&other));

    // And neither is the unverified connection a peer opened to the same address: sipx checked
    // nothing about that one, so it cannot stand in for a name it never verified.
    assert_ne!(one, ConnectionKey::new(peer, TransportKind::Tls));
}

/// RFC 3261 §18.1.1: the `Via` sent-by names where the sender expects responses to arrive,
/// *for the transport in use*. TLS is listened for on its own port (§19.1.2), so a request
/// dialled out over TLS that advertises the cleartext port sends any response that cannot
/// reuse the connection to a port speaking a different protocol.
#[tokio::test]
async fn a_tls_sent_by_names_the_tls_port() {
    use sipx_transport::{Config, TransportKind, bind};

    let ca = Ca::new();
    let (cert, key) = ca.issue(&[dns("localhost")], "localhost");
    let identity = Identity::from_pem(cert.as_bytes(), key.as_bytes()).expect("an identity");
    let server_tls = ServerTls::new(identity).expect("a server");

    let mut config = Config::new("127.0.0.1:0".parse().expect("valid"));
    config.tls_server = Some((server_tls, 0));
    let (endpoint, _rx) = bind(config).await.expect("binds");

    let cleartext_port = endpoint.local_addr().port();
    let tls_port = endpoint.tls_addr().expect("a TLS port was bound").port();
    assert_ne!(cleartext_port, tls_port, "the listeners are separate");

    let sent_by = endpoint.sent_by_for(TransportKind::Tls);
    assert!(
        sent_by.ends_with(&format!(":{tls_port}")),
        "a TLS Via must name the TLS port, not {sent_by}"
    );
    assert!(
        endpoint
            .sent_by_for(TransportKind::Udp)
            .ends_with(&format!(":{cleartext_port}")),
        "and the cleartext transports keep theirs"
    );
}
